# Resets the working tree to its initial state (as if it had just been cloned)
# and creates a Python virtual environment with all the requirements installed.
# All uncommitted changes and unversioned files will be lost (subject to
# confirmation by the user).
#
# Options:
#   - Untracked files: --no-clean (default), --clean
mongo-prepare ()
{
	( set -e;
	__mongo-check-wrkdir;
	__mongo-parse-args $@;

	if [[ ${__cmd_prefix} != echo && ${__clean} == 1 ]]; then
		echo "WARNING: All uncommitted changes and unversioned files will be lost";
		read -p "Are you sure you want to proceed? [y/N] ";
		[[ ${REPLY} =~ (y|Y) ]] || return 0;
	fi

	[[ -n ${VIRTUAL_ENV} ]] && ${__cmd_prefix} deactivate;
	if [[ ${__clean} == 1 ]]; then
		${__cmd_prefix} \git clean -fdx;
		${__cmd_prefix} ccache -C;
	fi

	${__cmd_prefix} \rm -rf ${MONGO_VENV_DIRNAME} node_modules;
	${__cmd_prefix} \python3 -m venv ${MONGO_VENV_DIRNAME};
	${__cmd_prefix} . ${MONGO_VENV_DIRNAME}/bin/activate;

	case ${__mongo_branch} in
		master)
			PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring;
			${__cmd_prefix} ${MONGO_VENV_DIRNAME}/bin/python3 -m pip install 'poetry==1.5.1';
			${__cmd_prefix} ${MONGO_VENV_DIRNAME}/bin/python3 -m poetry install --no-root --sync
		;;
		*)
			${__cmd_prefix} ${MONGO_VENV_DIRNAME}/bin/python3 -m pip install -r buildscripts/requirements.txt
		;;
	esac )
}

# Generates the `build.ninja` and `compile_commands.json` files, which are
# required by the underlying build system (i.e. Ninja) and the language server
# (i.e. ccls or clangd) respectively. The `mongo-build` function automatically
# generates these files when they do not exist. However, this function must be
# explicitly executed when a SCons configuration is changed (e.g. after adding
# or removing a source file) and consequently the `build.ninja` and
# `compile_commands.json` files must be recreated.
#
# Options:
#   - Compiler family: --clang (default), --gcc
#   - Compiling mode: --debug (default), --release
#   - Linking mode: --dynamic (default), --static
#   - All those of buildscripts/scons.py
mongo-configure ()
{
	( set -e;
	__mongo-check-wrkdir;
	__mongo-parse-args $@;

	__mongo-configure-ninja $@;
	__mongo-configure-compilation-db $@ )
}

# Builds all the executables. If the `build.ninja` or `compile_commands.json`
# file is missing (e.g. at first run), it is automatically generated. Source
# files are also formatted before being compiled.
#
# Options:
#   - Compiler family: --clang (default), --gcc
#   - Compiling mode: --debug (default), --release
#   - Linking mode: --dynamic (default), --static
#   - Executables to build: --all (default), --core
#   - Code formatting: --format (default), --no-format
#   - All those of ninja
mongo-build ()
{
	( set -e;
	__mongo-check-wrkdir;
	__mongo-parse-args $@;

	[[ ${__format} == 1 ]] && ${__cmd_prefix} mongo-format;

	[[ -f build.ninja ]] || __mongo-configure-ninja $@;
	[[ -f compile_commands.json ]] || __mongo-configure-compilation-db $@;
	${__cmd_prefix} ninja \
			-j400 \
			generated-sources \
			install-${__target} \
			${__args[@]} )
}

# Deletes all files generated by running `mongo-build` function (i.e.
# executables and object files). However, it does not delete the files
# corresponding to the build configuration (i.e. `build.ninja` and
# `compile_commands.json`).
#
# Options:
#   - Compiler family: --clang (default), --gcc
#   - Executables to delete: --all (default), --core
#   - All those of buildscripts/scons.py
mongo-clean ()
{
	( set -e;
	__mongo-check-wrkdir;
	__mongo-parse-args $@;

	${__cmd_prefix} ninja -t clean;
	${__cmd_prefix} ccache -C )
}

# Formats the source code according to the conversion adopted by all development
# teams.
#
# Options:
#   - All those of buildscripts/clang_format.py
mongo-format ()
{
	( set -e;
	__mongo-check-wrkdir;
	__mongo-check-venv;
	__mongo-parse-args $@;

	${__cmd_prefix} ./buildscripts/clang_format.py format-my )
}

mongo-find-suites ()
{
	( set -e;
	__mongo-check-wrkdir;
	__mongo-check-venv;
	__mongo-parse-args --master $@;

	${__cmd_prefix} ./buildscripts/resmoke.py find-suites \
			${__args[@]} )
}

# Runs on the current machine the infrastructure to process the specified
# JavaScript test. This proposes the last commit comment as a description of the
# patch, however it also allows to provide a custom message.
#
# Options:
#   - Concurrency: --single-task (default), --multi-task
#   - All those of buildscripts/resmoke.py
mongo-test-locally ()
{
	( set -e;
	__mongo-check-wrkdir;
	__mongo-check-venv;
	__mongo-parse-args --master $@;

	${__cmd_prefix} \rm -f executor.log fixture.log tests.log;
	set +e;
	${__cmd_prefix} ./buildscripts/resmoke.py run \
			--jobs=${__tasks} \
			--log=file \
			--storageEngine=wiredTiger \
			--storageEngineCacheSizeGB=0.5 \
			--mongodSetParameters='{logComponentVerbosity: {verbosity: 2}}' \
			--runAllFeatureFlagTests \
			${__args[@]} )
}

# Creates a new Evergreen path where it is possible to select the specific
# suites to run. By default, all required suites are pre-selected.
#
# Options:
#   - All those of evergreen patch
mongo-test-remotely ()
{
	( set -e;
	__mongo-check-wrkdir;
	__mongo-parse-args $@;

	msg=$(git log -n 1 --pretty=%B | head -n 1);
	if [[ ${__cmd_prefix} != echo ]]; then
		echo ${msg};
		read -p "Do you want change the title of this Evergreen patch? [y/N] ";
		if [[ ${REPLY} =~ (y|Y) ]]; then
			read -p "Type the custom title: " msg;
		fi;
	fi;

	${__cmd_prefix} evergreen patch \
			--project mongodb-mongo-${__mongo_branch} \
			--skip_confirm \
			--description "[$(git rev-parse --abbrev-ref HEAD)] ${msg}" \
			${__args[@]} )
}

################################################################################

mongo-merge ()
{
	( set -e;
	__mongo-check-wrkdir;
	__mongo-parse-args $@;

	${__cmd_prefix} evergreen commit-queue merge \
			--project mongodb-mongo-${__mongo_branch} \
			${__args[@]} )
}

mongo-monitor-buildnodes ()
{
	( set -e;
	__mongo-parse-args $@;

	${__cmd_prefix} icecream-sundae -s ${MONGO_ICECREAM_HOSTNAME}
	)
}

mongo-debug ()
{
	( set -e;
	__mongo-parse-args $@;

	echo __cmd_prefix=${__cmd_prefix};
	echo __clean=${__clean};
	echo __mongo_branch=${__mongo_branch};
	echo __toolchain=${__toolchain};
	echo __build_mode=${__build_mode};
	echo __link_model=${__link_model};
	echo __format=${__format};
	echo __target=${__target};
	echo __tasks=${__tasks};
	echo __args=${__args} )
}

################################################################################

###
### Global settings
###

MONGO_VENV_DIRNAME=${MONGO_VENV_DIRNAME:-'.venv'}
MONGO_ICECREAM_HOSTNAME=${MONGO_ICECREAM_HOSTNAME:-'iceccd-graviton.production.build.10gen.cc'}

###
### Internal functions
###

__mongo-check-wrkdir ()
{
	if [[ ! -d buildscripts ]]; then
		echo "ERROR: ${PWD} is not a mongo working directory" 1>&2;
		return 1;
	fi
}

__mongo-check-venv ()
{
	if [[ -z ${VIRTUAL_ENV} ]]; then
		if [[ -d ./${MONGO_VENV_DIRNAME} ]]; then
			echo "NOTE: Implicit activation of Python virtual environment";
			. ${MONGO_VENV_DIRNAME}/bin/activate;
		else
			echo "ERROR: No Python virtual environment to activate" 1>&2;
			return 1;
		fi
	fi
}

__mongo-parse-args ()
{
	[[ -z ${__parsed_args} ]] && __parsed_args=true || return 0;

	__cmd_prefix=;
	__clean=0;
	__mongo_branch=master;
	__toolchain=clang;
	__build_mode='--opt=off --dbg=on';
	__link_model='--link-model=dynamic';
	__format=1;
	__target=all;
	__tasks=1;
	__args=();

	while [[ $# -gt 0 ]]; do
		case $1 in
			--echo)
				__cmd_prefix=echo;
				shift
			;;
			--clean)
				__clean=1;
				shift
			;;
			--no-clean)
				__clean=0;
				shift
			;;
			--master)
				__mongo_branch=master;
				shift
			;;
			--v7.1)
				__mongo_branch=v7.1;
				shift
			;;
			--v7.0)
				__mongo_branch=v7.0;
				shift
			;;
			--v6.0)
				__mongo_branch=v6.0;
				shift
			;;
			--v5.0)
				__mongo_branch=v5.0;
				shift
			;;
			--v4.4)
				__mongo_branch=v4.4;
				shift
			;;
			--clang)
				__toolchain=clang;
				shift
			;;
			--gcc)
				__toolchain=gcc;
				shift
			;;
			--debug)
				__build_mode='--opt=off --dbg=on';
				shift
			;;
			--release)
				__build_mode='--opt=on --dbg=off';
				shift
			;;
			--dynamic)
				__link_model='--link-model=dynamic';
				shift
			;;
			--static)
				__link_model='--link-model=static';
				shift
			;;
			--format)
				__format=1;
				shift
			;;
			--no-format)
				__format=0;
				shift
			;;
			--all)
				__target=all;
				shift
			;;
			--core)
				__target=core;
				shift
			;;
			--mono-task)
				__tasks=1;
				shift
			;;
			--multi-task)
				__tasks=`cat /proc/cpuinfo | grep processor | wc -l`;
				shift
			;;
			*)
				__args+=($1);
				shift
			;;
		esac;
	done;
}

__mongo-configure-ninja ()
{
	( set -e;
	__mongo-check-wrkdir;
	__mongo-check-venv;
	__mongo-parse-args $@;

	${__cmd_prefix} ./buildscripts/scons.py \
			--variables-files=etc/scons/mongodbtoolchain_stable_${__toolchain}.vars \
			${__build_mode} \
			${__link_model} \
			--ninja generate-ninja \
			ICECC=icecc \
			CCACHE=ccache \
			${__args[@]} )
}

__mongo-configure-compilation-db ()
{
	( set -e;
	__mongo-check-wrkdir;
	__mongo-parse-args $@;

	${__cmd_prefix} ninja \
			compiledb \
			${__args[@]} )
}
